name: setup_cubit
description: Setup a Cubit installation for testing
inputs:
  cubit_download_url:
    description: URL where Cubit can be downloaded from
    required: true
  cubit_email:
    description: Email to activate cubit
    required: true
  cubit_password:
    description: Password to activate cubit
    required: true
runs:
  using: composite
  steps:
    - name: Download and unpack Cubit
      shell: bash
      run: |
        # We need these packages for cubit to work
        sudo apt update
        sudo apt install -y libglu1-mesa
        # Download cubit and extract it
        cd ${GITHUB_WORKSPACE}
        wget -q https://f002.backblazeb2.com/file/cubit-downloads/Coreform-Cubit/Releases/Linux/Coreform-Cubit-2025.3%2B58709-Lin64.tar.gz
        tar -xzf *.tar.gz
        # Save cubit root path for following steps
        CUBIT_FOLDER=$(find . -maxdepth 1 -type d -name "Coreform-Cubit-*" | head -n 1 | sed 's|^\./||')
        export CUBIT_ROOT="$(pwd)/$CUBIT_FOLDER"
        echo "CUBIT_ROOT=$CUBIT_ROOT" >> "$GITHUB_ENV"
        # Check if secrets are available
        if [[ -z "$CUBIT_PASSWORD" ]]; then
          echo "CUBIT_PASSWORD is empty or not injected"
          exit 1
        fi
        # Activate cubit
        $CUBIT_ROOT/bin/rlm_activate --login $CUBIT_EMAIL $CUBIT_PASSWORD
      env:
        CUBIT_EMAIL: ${{ secrets.CUBIT_EMAIL }}
        CUBIT_PASSWORD: ${{ secrets.CUBIT_PASSWORD }}
